version: '3'
services:
  flyway:
    image: flyway/flyway:6.3.1
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ${PWD}/launch/MetaTraceDB/sql_versions:/flyway/sql
      - ${PWD}/launch/MetaTraceDB/docker-flyway.config:/flyway/conf/flyway.config
    depends_on:
      - postgres
  postgres:
    image: postgres:12.2
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=123456!
    - POSTGRES_DB=demodb
  app:
    build: MetaTrace/
    ports:
      - "127.0.0.1:3000:3000"